const char gtk_builder_ui [] =
{
  "<?xml version=\"1.0\" ?><interface><requires lib=\"gtk\" version"
  "=\"4.0\"/><object id=\"DohodaOkno\" class=\"GtkApplicationWindow"
  "\"><property name=\"title\">DohodaProvedeniPrace GUI</property><c"
  "hild><object id=\"grid\" class=\"GtkGrid\"><property name=\"colu"
  "mn-spacing\">6</property><property name=\"row-spacing\">10</prop"
  "erty><property name=\"margin-bottom\">10</property><property nam"
  "e=\"margin-end\">10</property><property name=\"margin-start\">10"
  "</property><property name=\"margin-top\">10</property><!-- Nadpi"
  "sy --><child><object class=\"GtkLabel\" id=\"NadpisZamestnanecLa"
  "bel\"><property name=\"justify\">center</property><property name"
  "=\"use-markup\">True</property><property name=\"label\">Údaje o "
  "zaměstnanci</property><attributes><attribute name=\"weight\" val"
  "ue=\"bold\"/></attributes><layout><property name=\"column\">0</p"
  "roperty><property name=\"column-span\">2</property><property nam"
  "e=\"row\">2</property></layout></object></child><child><object c"
  "lass=\"GtkLabel\" id=\"NadpisPraceLabel\"><property name=\"justi"
  "fy\">center</property><property name=\"label\">Provedená práce</"
  "property><attributes><attribute name=\"weight\" value=\"bold\"/>"
  "</attributes><layout><property name=\"column\">2</property><prop"
  "erty name=\"column-span\">2</property><property name=\"row\">0</"
  "property></layout></object></child><child><object class=\"GtkLab"
  "el\" id=\"NadpisHodinyLabel\"><property name=\"justify\">center<"
  "/property><property name=\"label\">Počet hodin</property><attrib"
  "utes><attribute name=\"weight\" value=\"bold\"/></attributes><la"
  "yout><property name=\"column\">4</property></layout></object></c"
  "hild><child><object class=\"GtkLabel\" id=\"NadpisPoznamkaLabel\""
  "><property name=\"justify\">center</property><property name=\"la"
  "bel\">Poznámka</property><attributes><attribute name=\"weight\" "
  "value=\"bold\"/></attributes><layout><property name=\"column\">5"
  "</property><property name=\"column-span\">2</property></layout><"
  "/object></child><!-- Popisky --><child><object class=\"GtkLabel\""
  " id=\"DohodaLabel\"><property name=\"justify\">right</property><"
  "property name=\"label\">Název dohody:</property><property name=\""
  "halign\">end</property><layout><property name=\"column\">0</prop"
  "erty><property name=\"row\">1</property></layout></object></chil"
  "d><child><object class=\"GtkLabel\" id=\"JmenoLabel\"><property "
  "name=\"justify\">right</property><property name=\"label\">Jméno:"
  "</property><property name=\"halign\">end</property><layout><prop"
  "erty name=\"column\">0</property><property name=\"row\">3</prope"
  "rty></layout></object></child><child><object class=\"GtkLabel\" "
  "id=\"PrijmeniLabel\"><property name=\"justify\">right</property>"
  "<property name=\"label\">Příjmení:</property><property name=\"ha"
  "lign\">end</property><layout><property name=\"column\">0</proper"
  "ty><property name=\"row\">4</property></layout></object></child>"
  "<child><object class=\"GtkLabel\" id=\"KdeLabel\"><property name"
  "=\"justify\">right</property><property name=\"label\">Kde:</prop"
  "erty><property name=\"halign\">end</property><layout><property n"
  "ame=\"column\">0</property><property name=\"row\">5</property></"
  "layout></object></child><child><object class=\"GtkLabel\" id=\"R"
  "odneLabel\"><property name=\"justify\">right</property><property"
  " name=\"label\">Rodné číslo:</property><property name=\"halign\""
  ">end</property><layout><property name=\"column\">0</property><pr"
  "operty name=\"row\">6</property></layout></object></child><child"
  "><object class=\"GtkLabel\" id=\"BankaLabel\"><property name=\"j"
  "ustify\">right</property><property name=\"label\">Číslo bankovní"
  "ho účtu:</property><property name=\"halign\">end</property><layo"
  "ut><property name=\"column\">0</property><property name=\"row\">"
  "7</property></layout></object></child><child><object class=\"Gtk"
  "Label\" id=\"MistoLabel\"><property name=\"justify\">right</prop"
  "erty><property name=\"label\">Místo narození:</property><propert"
  "y name=\"halign\">end</property><layout><property name=\"column\""
  ">0</property><property name=\"row\">8</property></layout></objec"
  "t></child><child><object class=\"GtkLabel\" id=\"AdresaLabel\"><"
  "property name=\"justify\">right</property><property name=\"label"
  "\">Adresa:</property><property name=\"halign\">end</property><la"
  "yout><property name=\"column\">0</property><property name=\"row\""
  ">9</property></layout></object></child><child><object class=\"Gt"
  "kLabel\" id=\"PojistovnaLabel\"><property name=\"justify\">right"
  "</property><property name=\"label\">Zdravotní pojišťovna:</prope"
  "rty><property name=\"halign\">end</property><layout><property na"
  "me=\"column\">0</property><property name=\"row\">10</property></"
  "layout></object></child><!-- Údaje o dohodě --><child><object cl"
  "ass=\"GtkEntry\" id=\"NazevEntry\"><property name=\"width-chars\""
  ">20</property><property name=\"placeholder-text\">Tvorba GUI pro"
  " DPP</property><layout><property name=\"column\">1</property><pr"
  "operty name=\"row\">1</property></layout></object></child><child"
  "><object class=\"GtkEntry\" id=\"JmenoEntry\"><property name=\"w"
  "idth-chars\">20</property><property name=\"placeholder-text\">Fr"
  "anta</property><layout><property name=\"column\">1</property><pr"
  "operty name=\"row\">3</property></layout></object></child><child"
  "><object class=\"GtkEntry\" id=\"PrijmeniEntry\"><property name="
  "\"width-chars\">20</property><property name=\"placeholder-text\""
  ">Zakopal</property><layout><property name=\"column\">1</property"
  "><property name=\"row\">4</property></layout></object></child><c"
  "hild><object class=\"GtkEntry\" id=\"KdeEntry\"><property name=\""
  "width-chars\">20</property><property name=\"placeholder-text\">V"
  " Liberci</property><layout><property name=\"column\">1</property"
  "><property name=\"row\">5</property></layout></object></child><c"
  "hild><object class=\"GtkEntry\" id=\"RodneEntry\"><property name"
  "=\"width-chars\">20</property><property name=\"placeholder-text\""
  ">xxx/xxxx</property><layout><property name=\"column\">1</propert"
  "y><property name=\"row\">6</property></layout></object></child><"
  "child><object class=\"GtkEntry\" id=\"BankaEntry\"><property nam"
  "e=\"width-chars\">20</property><layout><property name=\"column\""
  ">1</property><property name=\"row\">7</property></layout></objec"
  "t></child><child><object class=\"GtkEntry\" id=\"MistoEntry\"><p"
  "roperty name=\"width-chars\">20</property><layout><property name"
  "=\"column\">1</property><property name=\"row\">8</property></lay"
  "out></object></child><child><object class=\"GtkEntry\" id=\"Adre"
  "saEntry\"><property name=\"width-chars\">20</property><layout><p"
  "roperty name=\"column\">1</property><property name=\"row\">9</pr"
  "operty></layout></object></child><child><object class=\"GtkEntry"
  "\" id=\"PojistovnaEntry\"><property name=\"width-chars\">20</pro"
  "perty><layout><property name=\"column\">1</property><property na"
  "me=\"row\">10</property></layout></object></child><!-- Datum -->"
  "<child><object class=\"GtkEntry\" id=\"Datum1\"><property name=\""
  "max-width-chars\">6</property><property name=\"width-chars\">6</"
  "property><property name=\"input-purpose\">number</property><prop"
  "erty name=\"placeholder-text\">23.9.</property><property name=\""
  "primary-icon-name\">x-office-calendar-symbolic</property><layout"
  "><property name=\"column\">2</property><property name=\"row\">1<"
  "/property></layout></object></child><child><object class=\"GtkEn"
  "try\" id=\"Datum2\"><property name=\"max-width-chars\">6</proper"
  "ty><property name=\"width-chars\">6</property><property name=\"i"
  "nput-purpose\">number</property><property name=\"primary-icon-na"
  "me\">x-office-calendar-symbolic</property><layout><property name"
  "=\"column\">2</property><property name=\"row\">2</property></lay"
  "out></object></child><child><object class=\"GtkEntry\" id=\"Datu"
  "m3\"><property name=\"max-width-chars\">6</property><property na"
  "me=\"width-chars\">6</property><property name=\"input-purpose\">"
  "number</property><property name=\"primary-icon-name\">x-office-c"
  "alendar-symbolic</property><layout><property name=\"column\">2</"
  "property><property name=\"row\">3</property></layout></object></"
  "child><child><object class=\"GtkEntry\" id=\"Datum4\"><property "
  "name=\"max-width-chars\">6</property><property name=\"width-char"
  "s\">6</property><property name=\"input-purpose\">number</propert"
  "y><property name=\"primary-icon-name\">x-office-calendar-symboli"
  "c</property><layout><property name=\"column\">2</property><prope"
  "rty name=\"row\">4</property></layout></object></child><child><o"
  "bject class=\"GtkEntry\" id=\"Datum5\"><property name=\"max-widt"
  "h-chars\">6</property><property name=\"width-chars\">6</property"
  "><property name=\"input-purpose\">number</property><property nam"
  "e=\"primary-icon-name\">x-office-calendar-symbolic</property><la"
  "yout><property name=\"column\">2</property><property name=\"row\""
  ">5</property></layout></object></child><child><object class=\"Gt"
  "kEntry\" id=\"Datum6\"><property name=\"max-width-chars\">6</pro"
  "perty><property name=\"width-chars\">6</property><property name="
  "\"input-purpose\">number</property><property name=\"primary-icon"
  "-name\">x-office-calendar-symbolic</property><layout><property n"
  "ame=\"column\">2</property><property name=\"row\">6</property></"
  "layout></object></child><child><object class=\"GtkEntry\" id=\"D"
  "atum7\"><property name=\"max-width-chars\">6</property><property"
  " name=\"width-chars\">6</property><property name=\"input-purpose"
  "\">number</property><property name=\"primary-icon-name\">x-offic"
  "e-calendar-symbolic</property><layout><property name=\"column\">"
  "2</property><property name=\"row\">7</property></layout></object"
  "></child><child><object class=\"GtkEntry\" id=\"Datum8\"><proper"
  "ty name=\"max-width-chars\">6</property><property name=\"width-c"
  "hars\">6</property><property name=\"input-purpose\">number</prop"
  "erty><property name=\"primary-icon-name\">x-office-calendar-symb"
  "olic</property><layout><property name=\"column\">2</property><pr"
  "operty name=\"row\">8</property></layout></object></child><child"
  "><object class=\"GtkEntry\" id=\"Datum9\"><property name=\"max-w"
  "idth-chars\">6</property><property name=\"width-chars\">6</prope"
  "rty><property name=\"input-purpose\">number</property><property "
  "name=\"primary-icon-name\">x-office-calendar-symbolic</property>"
  "<layout><property name=\"column\">2</property><property name=\"r"
  "ow\">9</property></layout></object></child><child><object class="
  "\"GtkEntry\" id=\"Datum10\"><property name=\"max-width-chars\">6"
  "</property><property name=\"width-chars\">6</property><property "
  "name=\"input-purpose\">number</property><property name=\"primary"
  "-icon-name\">x-office-calendar-symbolic</property><layout><prope"
  "rty name=\"column\">2</property><property name=\"row\">10</prope"
  "rty></layout></object></child><child><object class=\"GtkEntry\" "
  "id=\"Datum11\"><property name=\"max-width-chars\">6</property><p"
  "roperty name=\"width-chars\">6</property><property name=\"input-"
  "purpose\">number</property><property name=\"primary-icon-name\">"
  "x-office-calendar-symbolic</property><layout><property name=\"co"
  "lumn\">2</property><property name=\"row\">11</property></layout>"
  "</object></child><child><object class=\"GtkEntry\" id=\"Datum12\""
  "><property name=\"max-width-chars\">6</property><property name=\""
  "width-chars\">6</property><property name=\"input-purpose\">numbe"
  "r</property><property name=\"primary-icon-name\">x-office-calend"
  "ar-symbolic</property><layout><property name=\"column\">2</prope"
  "rty><property name=\"row\">12</property></layout></object></chil"
  "d><child><object class=\"GtkEntry\" id=\"Datum13\"><property nam"
  "e=\"max-width-chars\">6</property><property name=\"width-chars\""
  ">6</property><property name=\"input-purpose\">number</property><"
  "property name=\"primary-icon-name\">x-office-calendar-symbolic</"
  "property><layout><property name=\"column\">2</property><property"
  " name=\"row\">13</property></layout></object></child><child><obj"
  "ect class=\"GtkEntry\" id=\"Datum14\"><property name=\"max-width"
  "-chars\">6</property><property name=\"width-chars\">6</property>"
  "<property name=\"input-purpose\">number</property><property name"
  "=\"primary-icon-name\">x-office-calendar-symbolic</property><lay"
  "out><property name=\"column\">2</property><property name=\"row\""
  ">14</property></layout></object></child><child><object class=\"G"
  "tkEntry\" id=\"Datum15\"><property name=\"max-width-chars\">6</p"
  "roperty><property name=\"width-chars\">6</property><property nam"
  "e=\"input-purpose\">number</property><property name=\"primary-ic"
  "on-name\">x-office-calendar-symbolic</property><layout><property"
  " name=\"column\">2</property><property name=\"row\">15</property"
  "></layout></object></child><!-- Prace --><child><object class=\""
  "GtkEntry\" id=\"Prace1\"><property name=\"width-chars\">50</prop"
  "erty><property name=\"placeholder-text\">Kódování, grafický desi"
  "gn, testování</property><layout><property name=\"column\">3</pro"
  "perty><property name=\"row\">1</property></layout></object></chi"
  "ld><child><object class=\"GtkEntry\" id=\"Prace2\"><property nam"
  "e=\"width-chars\">50</property><layout><property name=\"column\""
  ">3</property><property name=\"row\">2</property></layout></objec"
  "t></child><child><object class=\"GtkEntry\" id=\"Prace3\"><prope"
  "rty name=\"width-chars\">50</property><layout><property name=\"c"
  "olumn\">3</property><property name=\"row\">3</property></layout>"
  "</object></child><child><object class=\"GtkEntry\" id=\"Prace4\""
  "><property name=\"width-chars\">50</property><layout><property n"
  "ame=\"column\">3</property><property name=\"row\">4</property></"
  "layout></object></child><child><object class=\"GtkEntry\" id=\"P"
  "race5\"><property name=\"width-chars\">50</property><layout><pro"
  "perty name=\"column\">3</property><property name=\"row\">5</prop"
  "erty></layout></object></child><child><object class=\"GtkEntry\""
  " id=\"Prace6\"><property name=\"width-chars\">50</property><layo"
  "ut><property name=\"column\">3</property><property name=\"row\">"
  "6</property></layout></object></child><child><object class=\"Gtk"
  "Entry\" id=\"Prace7\"><property name=\"width-chars\">50</propert"
  "y><layout><property name=\"column\">3</property><property name=\""
  "row\">7</property></layout></object></child><child><object class"
  "=\"GtkEntry\" id=\"Prace8\"><property name=\"width-chars\">50</p"
  "roperty><layout><property name=\"column\">3</property><property "
  "name=\"row\">8</property></layout></object></child><child><objec"
  "t class=\"GtkEntry\" id=\"Prace9\"><property name=\"width-chars\""
  ">50</property><layout><property name=\"column\">3</property><pro"
  "perty name=\"row\">9</property></layout></object></child><child>"
  "<object class=\"GtkEntry\" id=\"Prace10\"><property name=\"width"
  "-chars\">50</property><layout><property name=\"column\">3</prope"
  "rty><property name=\"row\">10</property></layout></object></chil"
  "d><child><object class=\"GtkEntry\" id=\"Prace11\"><property nam"
  "e=\"width-chars\">50</property><layout><property name=\"column\""
  ">3</property><property name=\"row\">11</property></layout></obje"
  "ct></child><child><object class=\"GtkEntry\" id=\"Prace12\"><pro"
  "perty name=\"width-chars\">50</property><layout><property name=\""
  "column\">3</property><property name=\"row\">12</property></layou"
  "t></object></child><child><object class=\"GtkEntry\" id=\"Prace1"
  "3\"><property name=\"width-chars\">50</property><layout><propert"
  "y name=\"column\">3</property><property name=\"row\">13</propert"
  "y></layout></object></child><child><object class=\"GtkEntry\" id"
  "=\"Prace14\"><property name=\"width-chars\">50</property><layout"
  "><property name=\"column\">3</property><property name=\"row\">14"
  "</property></layout></object></child><child><object class=\"GtkE"
  "ntry\" id=\"Prace15\"><property name=\"width-chars\">50</propert"
  "y><layout><property name=\"column\">3</property><property name=\""
  "row\">15</property></layout></object></child><child><object clas"
  "s=\"GtkEntry\" id=\"Hodiny1\"><property name=\"max-width-chars\""
  ">6</property><property name=\"width-chars\">6</property><propert"
  "y name=\"input-purpose\">number</property><property name=\"place"
  "holder-text\">10.5</property><layout><property name=\"column\">4"
  "</property><property name=\"row\">1</property></layout></object>"
  "</child><child><object class=\"GtkEntry\" id=\"Hodiny2\"><proper"
  "ty name=\"max-width-chars\">6</property><property name=\"width-c"
  "hars\">6</property><property name=\"input-purpose\">number</prop"
  "erty><property name=\"placeholder-text\">3</property><layout><pr"
  "operty name=\"column\">4</property><property name=\"row\">2</pro"
  "perty></layout></object></child><child><object class=\"GtkEntry\""
  " id=\"Hodiny3\"><property name=\"max-width-chars\">6</property><"
  "property name=\"width-chars\">6</property><property name=\"input"
  "-purpose\">number</property><layout><property name=\"column\">4<"
  "/property><property name=\"row\">3</property></layout></object><"
  "/child><child><object class=\"GtkEntry\" id=\"Hodiny4\"><propert"
  "y name=\"max-width-chars\">6</property><property name=\"width-ch"
  "ars\">6</property><property name=\"input-purpose\">number</prope"
  "rty><layout><property name=\"column\">4</property><property name"
  "=\"row\">4</property></layout></object></child><child><object cl"
  "ass=\"GtkEntry\" id=\"Hodiny5\"><property name=\"max-width-chars"
  "\">6</property><property name=\"width-chars\">6</property><prope"
  "rty name=\"input-purpose\">number</property><layout><property na"
  "me=\"column\">4</property><property name=\"row\">5</property></l"
  "ayout></object></child><child><object class=\"GtkEntry\" id=\"Ho"
  "diny6\"><property name=\"max-width-chars\">6</property><property"
  " name=\"width-chars\">6</property><property name=\"input-purpose"
  "\">number</property><layout><property name=\"column\">4</propert"
  "y><property name=\"row\">6</property></layout></object></child><"
  "child><object class=\"GtkEntry\" id=\"Hodiny7\"><property name=\""
  "max-width-chars\">6</property><property name=\"width-chars\">6</"
  "property><property name=\"input-purpose\">number</property><layo"
  "ut><property name=\"column\">4</property><property name=\"row\">"
  "7</property></layout></object></child><child><object class=\"Gtk"
  "Entry\" id=\"Hodiny8\"><property name=\"max-width-chars\">6</pro"
  "perty><property name=\"width-chars\">6</property><property name="
  "\"input-purpose\">number</property><layout><property name=\"colu"
  "mn\">4</property><property name=\"row\">8</property></layout></o"
  "bject></child><child><object class=\"GtkEntry\" id=\"Hodiny9\"><"
  "property name=\"max-width-chars\">6</property><property name=\"w"
  "idth-chars\">6</property><property name=\"input-purpose\">number"
  "</property><layout><property name=\"column\">4</property><proper"
  "ty name=\"row\">9</property></layout></object></child><child><ob"
  "ject class=\"GtkEntry\" id=\"Hodiny10\"><property name=\"max-wid"
  "th-chars\">6</property><property name=\"width-chars\">6</propert"
  "y><property name=\"input-purpose\">number</property><layout><pro"
  "perty name=\"column\">4</property><property name=\"row\">10</pro"
  "perty></layout></object></child><child><object class=\"GtkEntry\""
  " id=\"Hodiny11\"><property name=\"max-width-chars\">6</property>"
  "<property name=\"width-chars\">6</property><property name=\"inpu"
  "t-purpose\">number</property><layout><property name=\"column\">4"
  "</property><property name=\"row\">11</property></layout></object"
  "></child><child><object class=\"GtkEntry\" id=\"Hodiny12\"><prop"
  "erty name=\"max-width-chars\">6</property><property name=\"width"
  "-chars\">6</property><property name=\"input-purpose\">number</pr"
  "operty><layout><property name=\"column\">4</property><property n"
  "ame=\"row\">12</property></layout></object></child><child><objec"
  "t class=\"GtkEntry\" id=\"Hodiny13\"><property name=\"max-width-"
  "chars\">6</property><property name=\"width-chars\">6</property><"
  "property name=\"input-purpose\">number</property><layout><proper"
  "ty name=\"column\">4</property><property name=\"row\">13</proper"
  "ty></layout></object></child><child><object class=\"GtkEntry\" i"
  "d=\"Hodiny14\"><property name=\"max-width-chars\">6</property><p"
  "roperty name=\"width-chars\">6</property><property name=\"input-"
  "purpose\">number</property><layout><property name=\"column\">4</"
  "property><property name=\"row\">14</property></layout></object><"
  "/child><child><object class=\"GtkEntry\" id=\"Hodiny15\"><proper"
  "ty name=\"max-width-chars\">6</property><property name=\"width-c"
  "hars\">6</property><property name=\"input-purpose\">number</prop"
  "erty><layout><property name=\"column\">4</property><property nam"
  "e=\"row\">15</property></layout></object></child><!-- Poznámka -"
  "-><child><object class=\"GtkEntry\" id=\"Poznamka1\"><property n"
  "ame=\"max-width-chars\">10</property><property name=\"width-char"
  "s\">10</property><layout><property name=\"column\">5</property><"
  "property name=\"row\">1</property></layout></object></child><chi"
  "ld><object class=\"GtkEntry\" id=\"Poznamka2\"><property name=\""
  "max-width-chars\">10</property><property name=\"width-chars\">10"
  "</property><layout><property name=\"column\">5</property><proper"
  "ty name=\"row\">2</property></layout></object></child><child><ob"
  "ject class=\"GtkEntry\" id=\"Poznamka3\"><property name=\"max-wi"
  "dth-chars\">10</property><property name=\"width-chars\">10</prop"
  "erty><layout><property name=\"column\">5</property><property nam"
  "e=\"row\">3</property></layout></object></child><child><object c"
  "lass=\"GtkEntry\" id=\"Poznamka4\"><property name=\"max-width-ch"
  "ars\">10</property><property name=\"width-chars\">10</property><"
  "layout><property name=\"column\">5</property><property name=\"ro"
  "w\">4</property></layout></object></child><child><object class=\""
  "GtkEntry\" id=\"Poznamka5\"><property name=\"max-width-chars\">1"
  "0</property><property name=\"width-chars\">10</property><layout>"
  "<property name=\"column\">5</property><property name=\"row\">5</"
  "property></layout></object></child><child><object class=\"GtkEnt"
  "ry\" id=\"Poznamka6\"><property name=\"max-width-chars\">10</pro"
  "perty><property name=\"width-chars\">10</property><layout><prope"
  "rty name=\"column\">5</property><property name=\"row\">6</proper"
  "ty></layout></object></child><child><object class=\"GtkEntry\" i"
  "d=\"Poznamka7\"><property name=\"max-width-chars\">10</property>"
  "<property name=\"width-chars\">10</property><layout><property na"
  "me=\"column\">5</property><property name=\"row\">7</property></l"
  "ayout></object></child><child><object class=\"GtkEntry\" id=\"Po"
  "znamka8\"><layout><property name=\"column\">5</property><propert"
  "y name=\"row\">8</property></layout></object></child><child><obj"
  "ect class=\"GtkEntry\" id=\"Poznamka9\"><layout><property name=\""
  "column\">5</property><property name=\"row\">9</property></layout"
  "></object></child><child><object class=\"GtkEntry\" id=\"Poznamk"
  "a10\"><layout><property name=\"column\">5</property><property na"
  "me=\"row\">10</property></layout></object></child><child><object"
  " class=\"GtkEntry\" id=\"Poznamka11\"><layout><property name=\"c"
  "olumn\">5</property><property name=\"row\">11</property></layout"
  "></object></child><child><object class=\"GtkEntry\" id=\"Poznamk"
  "a12\"><layout><property name=\"column\">5</property><property na"
  "me=\"row\">12</property></layout></object></child><child><object"
  " class=\"GtkEntry\" id=\"Poznamka13\"><layout><property name=\"c"
  "olumn\">5</property><property name=\"row\">13</property></layout"
  "></object></child><child><object class=\"GtkEntry\" id=\"Poznamk"
  "a14\"><layout><property name=\"column\">5</property><property na"
  "me=\"row\">14</property></layout></object></child><child><object"
  " class=\"GtkEntry\" id=\"Poznamka15\"><layout><property name=\"c"
  "olumn\">5</property><property name=\"row\">15</property></layout"
  "></object></child><!-- Tlačítka --><child><object class=\"GtkBut"
  "ton\" id=\"TlacitkoUkoncit\"><property name=\"label\">Ukončit</p"
  "roperty><style><class name=\"destructive-action\"/></style><layo"
  "ut><property name=\"column\">4</property><property name=\"row\">"
  "16</property></layout></object></child><child><object class=\"Gt"
  "kButton\" id=\"TlacitkoVyplnit\"><property name=\"label\">Vyplni"
  "t výkaz</property><style><class name=\"suggested-action\"/></sty"
  "le><layout><property name=\"column\">5</property><property name="
  "\"row\">16</property></layout></object></child></object></child>"
  "</object></interface>"
};
